# Generated by Django 5.1.5 on 2025-02-06 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GuestBookPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('relation', models.CharField(max_length=64)),
                ('post', models.CharField(max_length=512)),
                ('time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
